[package]
name = "rcargo"
version = "0.1.0"
edition = "2024"

[dependencies]
toml = "0.8"
md5 = "0.7"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.0", features = ["derive"] }
