[package]
name = "rcargo"
version = "0.1.3"
edition = "2024"

[profile.release]
lto = true
strip = true

[dependencies]
toml = "0.9.2"
md5 = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.41", features = ["derive"] }
serde_json = "1.0.140"
