[package]
name = "rcargo"
version = "0.1.1"
edition = "2024"

[profile.release]
lto = true
strip = true

[dependencies]
toml = "0.8"
md5 = "0.7"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5", features = ["derive"] }
